from __future__ import absolute_import
from __future__ import print_function
from __future__ import division

import tensorflow as tf
import numpy as np

from tensorflow.examples.tutorials.mnist import input_data

import sys
import time

import cgan_model as cgan

sys.path.append('../')
import image_utils as iu


results = {
    'output': './gen_img/',
    'checkpoint': './model/checkpoint',
    'model': './model/CGAN-model.ckpt'
}

train_step = {
    'global_step': 500001,
    'logging_interval': 25000,
    'update_overpowered': 10,
}


def main():
    start_time = time.time()  # Clocking start

    # MNIST Dataset Load
    mnist = input_data.read_data_sets('./MNIST_data', one_hot=True)

    # GPU configure
    config = tf.ConfigProto()
    config.gpu_options.allow_growth = True

    with tf.Session(config=config) as s:
        # CGAN Model
        model = cgan.CGAN(s)

        # initializing
        s.run(tf.global_variables_initializer())

        sample_x, _ = mnist.train.next_batch(model.sample_num)
        sample_y = np.zeros(shape=[model.sample_num, model.n_classes])
        sample_y[:, 5] = 1   # Specify label what u wanna get
        sample_z = np.random.uniform(-1., 1.,  # range -1. ~ 1.
                                     [model.sample_num, model.z_dim]).astype(np.float32)

        d_overpowered = False
        for step in range(train_step['global_step']):
            batch_x, batch_y = mnist.train.next_batch(model.batch_size)
            batch_z = np.random.uniform(-1., 1.,  # range -1. ~ 1.
                                        size=[model.batch_size, model.z_dim]).astype(np.float32)

            # Update D network
            if not d_overpowered:
                _, d_loss = s.run([model.d_op, model.d_loss],
                                  feed_dict={
                                      model.x: batch_x,
                                      model.c: batch_y,
                                      model.z: batch_z
                                  })

            # Update G network
            _, g_loss = s.run([model.g_op, model.g_loss],
                              feed_dict={
                                  model.c: batch_y,
                                  model.z: batch_z
                              })

            # Logging
            if step % train_step['update_overpowered'] == 0:
                d_overpowered = d_loss < (g_loss / 3)

                if step % train_step['logging_interval'] == 0:
                    batch_x, batch_y = mnist.test.next_batch(model.batch_size)
                    batch_z = np.random.uniform(-1., 1.,  # range -1. ~ 1.
                                                [model.batch_size, model.z_dim]).astype(np.float32)

                    d_loss, g_loss, summary = s.run([model.d_loss, model.g_loss, model.merged],
                                                    feed_dict={
                                                        model.x: batch_x,
                                                        model.c: batch_y,
                                                        model.z: batch_z
                                                    })

                    # Update d_overpowered
                    d_overpowered = d_loss < (g_loss / 3)

                    # Print Loss
                    print("[+] Step %08d => " % step,
                          "D loss : {:.8f}".format(d_loss), " G loss : {:.8f}".format(g_loss),
                          "Overpowered :", d_overpowered)

                    # Training G model with sample image and noise
                    samples = s.run(model.g,
                                    feed_dict={
                                        model.c: sample_y,
                                        model.z: sample_z
                                    })

                    # Summary saver
                    model.writer.add_summary(summary, step)

                    # Export image generated by model G
                    sample_image_height = model.sample_size
                    sample_image_width = model.sample_size
                    sample_dir = results['output'] + 'train_{:08d}.png'.format(step)

                    # Generated image save
                    iu.save_images(samples,
                                   size=[sample_image_height, sample_image_width],
                                   image_path=sample_dir)

                    # Model save
                    model.saver.save(s, results['model'], global_step=step)

    end_time = time.time() - start_time  # Clocking end

    # Elapsed time
    print("[+] Elapsed time {:.8f}s".format(end_time))  # took about 600s on my machine

    # Close tf.Session
    s.close()


if __name__ == '__main__':
    main()
