from __future__ import absolute_import
from __future__ import print_function
from __future__ import division

import tensorflow as tf
import numpy as np

import sys
import time

import stargan_model as stargan
from dataset import DataIterator
from dataset import CelebADataSet as DataSet

sys.path.append('../')
import image_utils as iu

results = {
    'output': './gen_img/',
    'checkpoint': './model/checkpoint',
    'model': './model/StarGAN-model.ckpt'
}

train_step = {
    'epoch': 100,
    'batch_size': 16,
    'logging_step': 500,
}


def main():
    start_time = time.time()  # Clocking start

    # GPU configure
    config = tf.ConfigProto()
    config.gpu_options.allow_growth = True

    with tf.Session(config=config) as s:
        # pre-chosen
        attr_labels = [
            'Big_Nose', 'Black_Hair', 'Blond_Hair', 'Blurry', 'Brown_Hair',
            'Bushy_Eyebrows', 'Chubby', 'Double_Chin', 'Eyeglasses', 'Gray_Hair'
        ]

        # StarGAN Model
        model = stargan.StarGAN(s, attr_labels=attr_labels)  # StarGAN

        # Initializing
        s.run(tf.global_variables_initializer())

        # Celeb-A DataSet images
        ds = DataSet(input_height=64,
                     input_width=64,
                     input_channel=3,
                     mode='r')

        # x_A # Celeb-A
        img_a = ds.images
        attr_a = ds.labels

        # x_B # Celeb-A # copied from x_A
        img_b = img_a[:]
        attr_b = attr_a[:]

        # data_a(img_a, attr_a), data_b(img_b, attr_b) (concat)
        # data_a = DataSet.concat_data()
        # data_b = data_a[:]

        ds_a_iter = DataIterator(img_a, attr_a, train_step['batch_size'])
        ds_b_iter = DataIterator(img_b, attr_b, train_step['batch_size'])

        global_step = 0
        for epoch in range(train_step['epoch']):
            # learning rate decay
            lr_decay = 1.
            if epoch >= train_step['epoch']:
                lr_decay = (train_step['epoch'] - epoch) / (train_step['epoch'] / 2.)

            for x_a, y_a, x_b, y_b in ds_a_iter.iterate(), ds_b_iter.iterate():
                batch_a = DataSet.concat_data(x_a, y_a)
                batch_b = DataSet.concat_data(x_b, y_b)
                eps = np.random.rand(model.bach_size, 1, 1, 1)

                # Generate fake_B
                fake_b = s.run(model.fake_B, feed_dict={model.x_A: batch_a})

                # Update D network - 5 times
                for _ in range(5):
                    _, d_loss = s.run([model.d_op, model.d_loss],
                                      feed_dict={
                                          model.x_B: batch_b,
                                          model.y_B: y_b,
                                          model.fake_x_B: fake_b,
                                          model.lr_decay: lr_decay,
                                          model.epsilon: eps,
                                    })

                # Update G network - 1 time
                _, g_loss = s.run([model.g_op, model.g_loss],
                                  feed_dict={
                                      model.x_A: batch_a,
                                      model.x_B: batch_b,
                                      model.y_B: y_b,
                                      model.lr_decay: lr_decay,
                                      model.epsilon: eps,
                                  })

                if global_step % train_step['logging_step'] == 0:
                    # Summary
                    samples, d_loss, g_loss, summary = s.run([model.g, model.d_loss, model.g_loss, model.merged],
                                                             feed_dict={
                                                                 model.x_A: batch_a,
                                                                 model.x_B: batch_b,
                                                                 model.y_B: y_b,
                                                                 model.fake_x_B: fake_b,
                                                                 model.lr_decay: lr_decay,
                                                                 model.epsilon: eps,
                                                             })

                    # Print loss
                    print("[+] Epoch %04d Step %07d =>" % (epoch, global_step),
                          " D loss : {:.8f}".format(d_loss),
                          " G loss : {:.8f}".format(g_loss))

                    # Summary saver
                    model.writer.add_summary(summary, epoch)

                    # Export image generated by model G
                    sample_image_height = model.sample_size
                    sample_image_width = model.sample_size
                    sample_dir = results['output'] + 'train_{0}_{1}.png'.format(epoch, global_step)

                    # Generated image save
                    iu.save_images(samples,
                                   size=[sample_image_height, sample_image_width],
                                   image_path=sample_dir)

                    # Model save
                    model.saver.save(s, results['model'], global_step=global_step)

                global_step += 1

    end_time = time.time() - start_time  # Clocking end

    # Elapsed time
    print("[+] Elapsed time {:.8f}s".format(end_time))

    # Close tf.Session
    s.close()


if __name__ == '__main__':
    main()
